Homework 2
iloncka-ds/RecoService pull request #6
Opened 2022-11-22 15:25 UTC by PetrovitchSharp

2022-11-25 20:29 UTC, sharthZ23 requested changes
Не получилось замечания к самим ipynb написать, поэтому просуммирую здесь:
- По `UsersKFoldLeavePOut` все ок
- По `pFound` есть следующие замечания:
   - Не хватает сравнения скорости
   - Векторизированная версия должна оказаться быстрее,  сейчас кажется это не так
- По `MRR` есть следующие замечания:
   - В numba версии не используется numba.prange
   - В pandas версии используется targets, хотя у вас есть датафрейм 
   - В pandas версии df_recs сами на себя джоянтся, это грубая ошибка (вы просто таргет забыли использовать)
   - По сравнению погуглите, как сделать так, чтобы графики plotly могли остаться в ipynb после публикации на github

2022-11-26 08:20 UTC, sharthZ23 requested changes
За то, что мне нравится ваше оформление работы, дам вам еще одну попытку. Внимательно (!) прочитайте и сделайте выводы по вашему коду 
- https://numba.readthedocs.io/en/stable/user/faq.html#performance
- https://numba.readthedocs.io/en/stable/user/parallel.html
- https://iv-m.github.io/articles/numba-vs-numpy-sums/

2022-11-27 13:35 UTC, iloncka-ds commented
> За то, что мне нравится ваше оформление работы, дам вам еще одну попытку. Внимательно (!) прочитайте и сделайте выводы по вашему коду
> 
>     * https://numba.readthedocs.io/en/stable/user/faq.html#performance
> 
>     * https://numba.readthedocs.io/en/stable/user/parallel.html
> 
>     * https://iv-m.github.io/articles/numba-vs-numpy-sums/

Нашла решение проблемы с имплементацией функции с numba. Дело в том, что при добавлении опций (cache=True, parallel=True) и nb.prange ноутбук завершался аварийно. При решении проблемы помогли следующие ссылки и статьи: 
- https://numba.readthedocs.io/en/stable/user/faq.html#performance
-  https://github.com/numba/numba/issues/7652 "Overwrite of parallel loop index" with inlined functions and numba.prange
- https://stackoverflow.com/questions/61327371/error-in-numba-njit-when-indexing-numpy-array As I initially observed, numba does not like to index with a list. Converting the list to array works
- https://github.com/numba/numba/issues/8184  Wrong results with prange+parallel=True #8184 
- https://github.com/numba/numba/issues/7869 Strange Behaviour on Advanced Indexing 
Также еще добавила в оформление стилизацию таблицы с результатами, теперь сразу видно, что функцию с pandas нужно переделать )

2022-11-27 17:29 UTC, iloncka-ds commented
Я добавила приложение [ReviewNB](https://app.reviewnb.com/iloncka-ds/RecoService/pull/6/) для ревью ноутбуков. Также переписала функцию mrr_pandas.

2022-11-29 11:22 UTC, PetrovitchSharp commented
Все поднялось, графики стали такие, какими и должны были быть. Numba реализация выдавала раньше нули и бесконечности, теперь нормальные значения

2022-12-01 17:28 UTC, sharthZ23 approved these changes

2022-12-01 17:30 UTC, merged